BEGIN;

ALTER TABLE files
  ADD COLUMN IF NOT EXISTS subject VARCHAR(120) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS course VARCHAR(120) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS semester VARCHAR(60) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS unit_label VARCHAR(120) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS page_count INTEGER,
  ADD COLUMN IF NOT EXISTS is_featured BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_files_subject ON files(subject);
CREATE INDEX IF NOT EXISTS idx_files_featured ON files(is_featured);

COMMIT;
